./send.py --p UDP --src 10 --des 0 --m message+1 --sp 3 --dp 2
./send.py --p UDP --src 12 --des 12 --m message+2 --sp 4 --dp 3
./send.py --p TCP --src 12 --des 14 --m message+3 --sp 2 --dp 1
./send.py --p UDP --src 14 --des 3 --m message+4 --sp 2 --dp 1
./send.py --p TCP --src 3 --des 8 --m message+5 --sp 1 --dp 2
./send.py --p UDP --src 14 --des 8 --m message+6 --sp 4 --dp 4
./send.py --p UDP --src 7 --des 13 --m message+7 --sp 1 --dp 1
./send.py --p UDP --src 8 --des 13 --m message+8 --sp 1 --dp 2
./send.py --p TCP --src 0 --des 8 --m message+9 --sp 1 --dp 4
./send.py --p TCP --src 10 --des 13 --m message+10 --sp 2 --dp 1
./send.py --p UDP --src 4 --des 2 --m message+11 --sp 1 --dp 4
./send.py --p TCP --src 10 --des 8 --m message+12 --sp 3 --dp 3
./send.py --p UDP --src 6 --des 9 --m message+13 --sp 4 --dp 2
./send.py --p UDP --src 7 --des 2 --m message+14 --sp 3 --dp 4
./send.py --p TCP --src 4 --des 14 --m message+15 --sp 4 --dp 1
./send.py --p UDP --src 9 --des 11 --m message+16 --sp 3 --dp 4
./send.py --p UDP --src 12 --des 0 --m message+17 --sp 1 --dp 1
./send.py --p TCP --src 5 --des 8 --m message+18 --sp 3 --dp 3
./send.py --p TCP --src 4 --des 6 --m message+19 --sp 1 --dp 1
./send.py --p UDP --src 1 --des 3 --m message+20 --sp 4 --dp 4
